config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users
  root to: 'transactions#index'
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end
  get 'transactions/import', to: 'transactions#import_form', as: 'transaction_import_form'
  post 'transactions/import', to: 'transactions#import', as: 'transaction_import'
  post 'transactions/export', to: 'transactions#export', as: 'transaction_export'
  resources :transactions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  include Xls

  belongs_to :user
  belongs_to :category
  has_one_attached :receipt
  validates :name, :amount, :category_id, :transaction_date, presence: true
  validates :amount, numericality: { greater_than: 0 }

  attr_accessor :remove_receipt
  before_save :check_remove_receipt
  after_create :send_email

  def check_remove_receipt
    puts "remove_receipt: #{remove_receipt}"
    receipt.purge if remove_receipt == '1'
  end

  def self.generate_xls(transactions)
    xls_rows = transactions.map do |transaction|
      category_name = Category.find(transaction.category_id).name
      [
        transaction.name,
        transaction.amount,
        transaction.description,
        category_name,
        transaction.transaction_date
      ]
    end
    headers = ['Name', 'Amount', 'Description', 'Category', 'Transaction Date']
    xls = Xls.export(headers, xls_rows)
  end

  def self.create_from_import(file, current_user)
    transactions = Xls.import(file)
    transactions.each_with_index do |transaction, index|
      next if index.zero?

      category_id = Category.find_by(name: transaction[3])&.id || Category.find_by(name: 'Other')&.id
      begin
        create!(
          name: transaction[0],
          amount: transaction[1],
          description: transaction[2],
          category_id: category_id,
          transaction_date: transaction[4],
          user_id: current_user.id
        )
      rescue => e
        return { error: "Error in row #{index + 1}: #{e.message}" }
      end
    end
  end

  def send_email
    SendTransactionEmailJob.perform_later(id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :authenticate_user!

  def index
    @q = Transaction.ransack(params[:q])
    @transactions = @q.result(distinct: true).where(user_id: current_user.id).order(transaction_date: :desc)
  end

  def show
    @transaction = Transaction.find(params[:id])
  end

  def new
    @transaction = Transaction.new
    @transaction.user = current_user
    @categories = Category.all
  end

  def create
    @transaction = Transaction.new(transaction_params)
    @transaction.user = current_user
    if @transaction.save
      redirect_to transaction_path(@transaction)
    else
      flash[:error] = @transaction.errors.full_messages.to_sentence
      redirect_to new_transaction_path
    end
  end

  def edit
    @transaction = Transaction.find(params[:id])
    @categories = Category.all
  end

  def update
    @transaction = Transaction.find(params[:id])
    if @transaction.update(transaction_params)
      redirect_to transaction_path(@transaction)
    else
      flash[:error] = @transaction.errors.full_messages.to_sentence
      redirect_to edit_transaction_path
    end
  end

  def destroy
    @transaction = Transaction.find(params[:id])
    @transaction.destroy
    redirect_to transactions_path
  end

  def import_form
  end

  def import
    file = params[:file]
    result = Transaction.create_from_import(file, current_user)
    flash[:error] = result[:error] if result[:error]
    redirect_to transactions_path
  end

  def export
    transactions = Transaction.where(user_id: current_user.id).order(transaction_date: :desc)
    xls = Transaction.generate_xls(transactions)
    send_data xls, filename: 'transactions.xlsx'
  end

  private

  def transaction_params
    params.require(:transaction).permit(:name, :amount, :description, :category_id, :transaction_date, :receipt, :remove_receipt)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/transaction_helper.rb
module TransactionHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Finance Tracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar-dark bg-dark">
      <div class="col-md-7 mx-auto navbar">
        <%= link_to "Home", transactions_path, class: "text-white text-decoration-none" %>
        <% if user_signed_in? %>
          <%= link_to "New Transaction", new_transaction_path, class: "text-white text-decoration-none" %>
          <%= link_to "Import Transactions", transaction_import_form_path, class: "text-white text-decoration-none" %> 
          <%= link_to "Export Transactions", transaction_export_path, method: :post, class: "text-white text-decoration-none" %>
          <%= link_to "Profile", edit_user_registration_path, class: "text-white text-decoration-none" %>
          <div class="ml-auto">
            <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-light" %>
          </div>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path,  class: "text-white text-decoration-none" %>
          <%= link_to "Login", new_user_session_path, class: "btn btn-light" %>
        <% end %>
      </div>
    </nav>

    <div class="container">
      <% if notice %>
        <div class="col-md-6 mx-auto mt-4">
          <div class="alert alert-warning">
            <p><%= notice %></p>
        </div>
      <% end %>

      <% if alert %>
        <div class="col-md-6 mx-auto mt-4">
          <div class="alert alert-danger">
            <p><%= alert %></p>
          </div>
        </div>
      <% end %>
    </div>

    <%= yield %>
    <div class="mt-5"></div>
  </body>
</html>

app/views/transaction/index.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <button class="btn btn-dark mb-3">
        New Transaction
      </button>
      <div class="card">
        <div class="card-header bg-dark text-white">
          Transactions
        </div>
        <div class="card-body">
          <% @transactions.each_with_index do |transaction, index| %>
            <% if index == @transactions.length - 1 %>
                <div class="mb-3">
            <% else %>
                <div class="mb-3 border-bottom">
            <% end %>
              <h4><%= link_to transaction.name, transaction, class: 'text-dark text-decoration-none'  %></h4>
              <p class="text-muted mb-2"><strong>Amount:</strong> <%= number_to_currency(transaction.amount) %></p>
              <p class="text-muted mb-2"><strong>Description:</strong> <%= transaction.description %></p>
              <p class="text-muted"><strong>Date:</strong> <%= transaction.transaction_date.strftime('%B %d, %Y') %></p>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/transactions/_flash_messages.html.erb
<% if flash[:error] %>
    <div class="alert alert-danger">
        <%= flash[:error] %>
    </div>
<% end %>

app/views/transactions/_form_fields.html.erb
<div class="form-group mb-4">
  <%= form.label :name %>
  <%= form.text_field :name, class: 'form-control', placeholder: 'Enter name', required: true %>
</div>

<div class="form-group mb-4">
  <%= form.label :amount %>
  <%= form.number_field :amount, class: 'form-control', placeholder: 'Enter amount', required: true %>
</div>

<div class="form-group mb-4">
  <%= form.label :description %>
  <%= form.text_field :description, class: 'form-control', placeholder: 'Enter description'%>
</div>

<div class="form-group mb-4">
  <%= form.label :category_id %>
  <%= form.collection_select :category_id, @categories, :id, :name, { prompt: 'Select category' }, class: 'form-control' %>
</div>

<div class="form-group mb-4">
  <%= form.label :transaction_date %>
  <%= form.date_field :transaction_date, class: 'form-control', required: true, max: Date.today, value: Date.today  %>
</div>

<div class="form-group mb-4">
  <%= form.label :receipt %>
  <%= form.file_field :receipt, class: 'form-control' %>
  <% if @transaction.receipt.attached? %>
    <p>Current file: <%= @transaction.receipt.filename %></p>
    <%= form.check_box :remove_receipt %> Remove receipt
  <% end %>
</div>

app/views/transactions/edit.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="card">
        <div class="card-header">
          New Transaction
        </div>
        <div class="card-body">
          <%= form_with(model: @transaction, local: true) do |form| %>
            <div class="form-group mb-4">
              <%= form.label :name %>
              <%= form.text_field :name, class: 'form-control', placeholder: 'Enter name', required: true %>
            </div>
            <div class="form-group mb-4">
              <%= form.label :amount %>
              <%= form.number_field :amount, class: 'form-control', placeholder: 'Enter amount', required: true %>
            </div>
            <div class="form-group mb-4">
              <%= form.label :description %>
              <%= form.text_field :description, class: 'form-control', placeholder: 'Enter description', required: true %>
            </div>
            <div class="form-group mb-4">
              <%= form.label :category_id %>
              <%= form.collection_select :category_id, @categories, :id, :name, { prompt: 'Select category' }, class: 'form-control' %>
            </div>
            <div class="form-group mb-4">
              <%= form.label :transaction_date %>
              <%= form.date_field :transaction_date, class: 'form-control', required: true, max: Date.today, value: Date.today  %>
            </div>
            <div class="form-group mb-4">
              <%= form.label :receipt %>
              <%= form.file_field :receipt, class: 'form-control' %>
            </div>
            <%= form.submit 'Edit Transaction', class: 'btn btn-dark' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/transactions/edit.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <%= render 'flash_messages' %>
      <div class="card">
        <div class="card-header">
          Edit Transaction
        </div>
        <div class="card-body">
          <%= form_with(model: @transaction, local: true) do |form| %>
            <%= render 'form_fields', form: form %>
            <%= form.submit 'Create Transaction', class: 'btn btn-dark' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/transactions/import_form.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <h2 class="mb-4">Import XLS Transactions</h2>
      <%= render 'flash_messages' %>
      <%= link_to 'Download Template', '/templates/finance_tracker_template.xlsx', class: 'btn btn-secondary mb-4' %>
      <%= form_with(url: transaction_import_path, multipart: true) do |form| %>
        <div class="mb-3">
          <%= form.label :file, class: 'form-label' %>
          <%= form.file_field :file, class: 'form-control', accept: '.xls, .xlsx' %>
        </div>
        <%= form.submit "Import", class: 'btn btn-dark w-100' %>
      <% end %>
    </div>
  </div>
</div>

app/views/transactions/index.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <button class="btn btn-dark mb-3">
        <%= link_to 'New Transaction', new_transaction_path, class: 'text-white text-decoration-none' %>
      </button>
      <div class="d-flex">
        <%= search_form_for @q, url: transactions_path, method: :get, class: 'input-group rounded mb-3 w-50' do |f| %>
          <%= f.search_field :name_cont, class: 'form-control rounded', placeholder: 'Search' %>
          <%= f.collection_select :category_id_eq, Category.all, :id, :name, { include_blank: 'All Categories' }, class: 'form-control rounded ms-2' %>
          <button class="input-group-text border-0 btn ms-2">
            <i class="fas fa-search"></i>
          </button>
        <% end %>
      </div>
      <div class="card">
        <div class="card-header bg-dark text-white">
          Transactions
        </div>
        <div class="card-body">
          <% @transactions.each_with_index do |transaction, index| %>
            <% if index == @transactions.length - 1 %>
                <div class="mb-3">
            <% else %>
                <div class="mb-3 border-bottom">
            <% end %>
              <h4><%= link_to transaction.name, transaction, class: 'text-dark text-decoration-none'  %></h4>
              <p class="text-muted mb-2"><strong>Amount:</strong> <%= number_to_currency(transaction.amount, unit: "Rp", format: "%u %n") %></p>
              <p class="text-muted mb-2"><strong>Description:</strong> <%= transaction.description %></p>
              <p class="text-muted mb-2"><strong>Category:</strong> <%= transaction.category.name %></p>
              <p class="text-muted"><strong>Date:</strong> <%= transaction.transaction_date.strftime('%B %d, %Y') %></p>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/transactions/index.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <div class="d-flex col-md-6">
        <%= search_form_for @q, url: transactions_path, method: :get, class: 'input-group rounded mb-3 w-100' do |f| %>
          <%= f.search_field :name_or_description_cont, class: 'form-control rounded', placeholder: 'Search' %>
          <%= f.collection_select :category_id_eq, Category.all, :id, :name, { include_blank: 'All Categories' }, class: 'form-control rounded ms-2' %>
          <button class="input-group-text border-0 btn ms-2">
            <i class="fas fa-search"></i>
          </button>
        <% end %>
      </div>
      <div class="card">
        <div class="card-header bg-dark text-white">
          Transactions
        </div>
        <div class="card-body">
          <% @transactions.each_with_index do |transaction, index| %>
            <% if index == @transactions.length - 1 %>
                <div class="mb-3">
            <% else %>
                <div class="mb-3 border-bottom">
            <% end %>
              <h4><%= link_to transaction.name, transaction, class: 'text-dark text-decoration-none'  %></h4>
              <p class="text-muted mb-2"><strong>Amount:</strong> <%= number_to_currency(transaction.amount, unit: "Rp", format: "%u %n") %></p>
              <p class="text-muted mb-2"><strong>Description:</strong> <%= transaction.description %></p>
              <p class="text-muted mb-2"><strong>Category:</strong> <%= transaction.category.name %></p>
              <p class="text-muted"><strong>Date:</strong> <%= transaction.transaction_date.strftime('%B %d, %Y') %></p>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/transactions/new.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="card">
        <div class="card-header">
          New Transaction
        </div>
        <div class="card-body">
          <%= form_with(model: @transaction, local: true) do |form| %>
            <div class="form-group mb-4">
              <%= form.label :name %>
              <%= form.text_field :name, class: 'form-control', placeholder: 'Enter name', required: true %>
            </div>
            <div class="form-group mb-4">
              <%= form.label :amount %>
              <%= form.number_field :amount, class: 'form-control', placeholder: 'Enter amount', required: true %>
            </div>
            <div class="form-group mb-4">
              <%= form.label :description %>
              <%= form.text_field :description, class: 'form-control', placeholder: 'Enter description', required: true %>
            </div>
            <div class="form-group mb-4">
              <%= form.label :category_id %>
              <%= form.collection_select :category_id, @categories, :id, :name, { prompt: 'Select category' }, class: 'form-control' %>
            </div>
            <div class="form-group mb-4">
              <%= form.label :transaction_date %>
              <%= form.date_field :transaction_date, class: 'form-control', required: true, max: Date.today, value: Date.today  %>
            </div>
            <div class="form-group mb-4">
              <%= form.label :receipt %>
              <%= form.file_field :receipt, class: 'form-control' %>
            </div>
            <%= form.submit 'Create Transaction', class: 'btn btn-dark' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/transactions/new.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <%= render 'flash_messages' %>
      <div class="card">
        <div class="card-header">
          New Transaction
        </div>
        <div class="card-body">
          <%= form_with(model: @transaction, local: true) do |form| %>
            <%= render 'form_fields', form: form %>
            <%= form.submit 'Create Transaction', class: 'btn btn-dark' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/transactions/show.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="card">
        <div class="card-header bg-dark text-white">
          Transaction Details
        </div>
        <div class="card-body">
          <h4><strong><%= @transaction.name %></strong></h4>
          <p><strong>Amount:</strong> <%= number_to_currency(@transaction.amount, unit: "Rp", format: "%u %n") %></p>
          <p><strong>Description:</strong> <%= @transaction.description %></p>
          <p><strong>Category:</strong> <%= @transaction.category.name %></p>
          <p><strong>Transaction Date:</strong> <%= @transaction.transaction_date.strftime('%B %d, %Y') %></p>
          <% if @transaction.receipt.attached? %>
            <p><strong>Receipt:</strong></p>
            <%= link_to url_for(@transaction.receipt), target: "_blank" do %>
              <%= image_tag @transaction.receipt, class: 'img-fluid mb-4 d-block w-25' %>
            <% end %>
          <% else %>
            <p><strong>Receipt:</strong> No receipt attached.</p>
          <% end %>
          <button class="btn btn-dark"><%= link_to 'Edit', edit_transaction_path(@transaction), class: 'text-white text-decoration-none' %></button>
          <button class="btn btn-danger"><%= link_to 'Delete', transaction_path(@transaction), method: :delete, data: { confirm: 'Are you sure?' }, class: 'text-white text-decoration-none' %></button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/transactions/show.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="card">
        <div class="card-header bg-dark text-white">
          Transaction Details
        </div>
        <div class="card-body">
          <h4><strong><%= @transaction.name %></strong></h4>
          <p><strong>Amount:</strong> <%= number_to_currency(@transaction.amount, unit: "Rp", format: "%u %n") %></p>
          <p><strong>Description:</strong> <%= @transaction.description %></p>
          <p><strong>Category:</strong> <%= @transaction.category.name %></p>
          <p><strong>Transaction Date:</strong> <%= @transaction.transaction_date.strftime('%B %d, %Y') %></p>
          <% if @transaction.receipt.attached? %>
            <p><strong>Receipt:</strong></p>
            <%= link_to url_for(@transaction.receipt), target: "_blank" do %>
              <%= image_tag @transaction.receipt, class: 'img-fluid mb-4 d-block w-25' %>
            <% end %>
          <% else %>
            <p><strong>Receipt:</strong> No receipt attached.</p>
          <% end %>
          <button class="btn btn-dark"><%= link_to 'Edit', edit_transaction_path(@transaction), class: 'text-white text-decoration-none' %></button>
          <button class="btn btn-danger"><%= link_to 'Delete', transaction_path(@transaction), method: :delete, data: { confirm: 'Are you sure?' }, class: 'text-white text-decoration-none' %></button>
        </div>
      </div>
    </div>
  </div>
</div>